runs:
  using: "composite"
  steps:
    - name: Install Azure CLI
      shell: bash
      run: |
        set -eux
        apt-get update
        apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://aka.ms/InstallAzureCLIDeb | bash
        az version

    - name: Install kubectl & kubelogin
      shell: bash
      run: |
        KUBECTL_VER="$(curl -Ls https://dl.k8s.io/release/stable.txt)"
        curl -L "https://dl.k8s.io/release/${KUBECTL_VER}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.25/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip
        sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
        sudo chmod +x /usr/local/bin/kubelogin
        kubelogin --version
