trigger: none

pool:
  name: SelfHosted

variables:
  - name: DOCKER_BUILDKIT
    value: 1
  - group: integrationTest

resources:
  repositories:
    - repository: common-templates
      type: git
      name: Common Modules/common-templates

jobs:
  - template: _build.yml
    parameters:
      canPush: true
      imageSuffix: "/unstable"
