{
 "title": "MZinga - API Performance Dashboard",
 "description": "Get information for api performance",
 "tags": [
  "api",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total RPS all tenants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[$__range])) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  { "title": "$tenant API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "tenant" },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=~\"mzinga-api-svc.$tenant:3000\"}[5m])",
     "legendFormat": "$tenant"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "rate(nodejs_external_memory_bytes{instance=~\"mzinga-api-svc.$tenant:3000\"}[$__range]) / 1024",
     "legendFormat": "$tenant"
    }
   ]
  },
  {
   "title": "Top 10 Slowest APIs (Avg Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10,(\n  sum by (path, method, tenant) (\n    rate(http_request_duration_seconds_sum{status_code=~\"2..\", tenant=\"$tenant\"}[$__range])\n  )\n  /\n  sum by (path, method, tenant) (\n    rate(http_request_duration_seconds_count{status_code=~\"2..\",tenant=\"$tenant\"}[$__range])\n  )\n))"
    }
   ]
  },
  {
   "title": "Top 5 Busiest APIs (RPS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (path, tenant, method) (rate(http_request_duration_seconds_count{ tenant=\"$tenant\"}[$__range])))",
     "legendFormat": "{{ uri }} {{ method }}"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests (Max Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max by (path,tenant,method) (max_over_time(http_request_duration_seconds_sum{method!=\"\", path!=\"\", tenant=\"$tenant\", status_code=~\"2..\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{tenant=\"$tenant\"}[5m])) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  }
 ]
}