{
 "title": "MZinga / Workload Monitoring",
 "tags": [
  "monitoring",
  "workload"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "query_result(kube_pod_labels{label_app=~\"mzinga.*\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) /\n(sum by (namespace)  (\n(sum by (pod) (\nkube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$tenant\", resource=\"cpu\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) / (sum by (namespace)  (\n(sum by (pod) (\nkube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$tenant\", resource=\"cpu\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\",container!=\"\", image!=\"\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) / (sum by (namespace)  (\n(sum by (pod) (\nkube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$tenant\", resource=\"memory\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})))"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\",container!=\"\", image!=\"\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) / (sum by (namespace)  (\n(sum by (pod) (\nkube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$tenant\", resource=\"memory\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})))"
    }
   ]
  },
  {
   "title": "Number of successful requests on: $tenant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"2.*|3.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Number of 4xx requests on: $tenant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"4.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Number of 5xx requests on: $tenant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"5.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors (4xx and 5xx) rate %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"4.*\"}[$__range])) + sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"5.*\"}[$__range]))) / sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$tenant\", status=~\"2.*\"}[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests with 4xx status code on: $tenant",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "filters": [
      { "id": "89639b59", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.tenant=\"$tenant\" && .http.status_code>=400 && .http.status_code<500}"
    }
   ]
  },
  {
   "title": "Requests with 5xx status code on: $tenant",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "filters": [
      { "id": "89639b59", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.tenant=\"$tenant\" && .http.status_code>=500 && .http.status_code<600}"
    }
   ]
  },
  {
   "title": "Requests information on: $tenant",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "filters": [
      { "id": "89639b59", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.tenant=\"$tenant\" && .http.url!~\".*/probes.*\"}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$tenant\", type=\"hard\",resource=\"requests.cpu\", pod=~\"mzinga-.*\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$tenant\", type=\"hard\",resource=\"limits.cpu\", pod=~\"mzinga-.*\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "(\n    sum by (pod) (\n      cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "(\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"} / \n(sum by (pod) (\ncluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$tenant\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})"
    },
    {
     "expr": "(\n    sum by (pod) (\n      cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "(\n    sum by (pod) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"} / \n(sum by (pod) (\ncluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$tenant\"}\n) * on (pod) \ngroup_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by (namespace)  ((\n    sum by (pod) (\n      container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", container!=\"\", image!=\"\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"})) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$tenant\", type=\"hard\",resource=\"requests.memory\", pod=~\"mzinga-.*\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$tenant\", type=\"hard\",resource=\"limits.memory\", pod=~\"mzinga-.*\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n    sum by (pod) (\n      container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", container!=\"\", image!=\"\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "(\n    sum by (pod) (\n      cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$tenant\"}\n    )\n  )\n* on (pod) group_left (mzinga_label)\n  kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "\n        (\n          sum by (pod) (\n            container_memory_working_set_bytes{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}\n  \n/\n  \n        (\n          sum by (pod) (\n            cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}\n    "
    },
    {
     "expr": "  \n        (\n          sum by (pod) (\n            cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "  \n        (\n          sum by (pod) (\n            container_memory_working_set_bytes{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}\n   \n/\n  \n        (\n          sum by (pod) (\n            cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "  \n        (\n          sum by (pod) (\n            container_memory_rss{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "  \n        (\n          sum by (pod) (\n            container_memory_cache{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    },
    {
     "expr": "  \n        (\n          sum by (pod) (\n            container_memory_swap{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$tenant\"}\n          )\n        )\n      * on (pod) group_left (mzinga_label)\n        kube_pod_labels{job=\"kube-state-metrics\",label_app=~\"mzinga*\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{host=~\".*$tenant.mzinga.io\"}) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 73 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=~\"$tenant\", host=~\".*mzinga.io\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=~\"$tenant\", host=~\".*mzinga.io\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=~\"$tenant\", host=~\".*mzinga.io\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{exported_namespace=~\"$tenant\", host=~\".*mzinga.io\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{exported_namespace=~\"$tenant\", host=~\".*mzinga.io\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rate of Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Storage IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IOPS(Reads)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ThroughPut (Read)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS(Writes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ThroughPut (Write)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$tenant\", pod=~\"mzinga-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}